service: floss
provider: aws
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  serverless-offline:
    httpPort: 3001
functions:
  contract-get:
    handler: out/contract_get.handler
    events:
      - http:
          path: contract
          method: get
          cors: true
  contract-put:
    handler: out/contract_put.handler
    events:
      - http:
          path: contract
          method: put
          cors: true
  contracts-get:
    handler: out/contracts_get.handler
    events:
      - http:
          path: contracts
          method: get
          cors: true
  stripe-setup-intent-post:
    handler: out/stripe-setup-intent_post.handler
    events:
      - http:
          path: stripe-setup-intent
          method: post
          cors: true