service: floss
provider: aws
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  serverless-offline:
    httpPort: 3001
functions:
  aws-check-domain-get:
    handler: out/aws-check-domain_get.handler
    events:
      - http:
          path: aws-check-domain
          method: get
          cors: true
  contract-get:
    handler: out/contract_get.handler
    events:
      - http:
          path: contract
          method: get
          cors: true
  contract-by-email-get:
    handler: out/contract-by-email_get.handler
    events:
      - http:
          path: contract-by-email
          method: get
          cors: true
  contract-post:
    handler: out/contract_post.handler
    events:
      - http:
          path: contract
          method: post
          cors: true
  contract-put:
    handler: out/contract_put.handler
    events:
      - http:
          path: contract
          method: put
          cors: true
  contracts-get:
    handler: out/contracts_get.handler
    events:
      - http:
          path: contracts
          method: get
          cors: true
  issue-get:
    handler: out/issue_get.handler
    events:
      - http:
          path: issue
          method: get
          cors: true
  project-get:
    handler: out/project_get.handler
    events:
      - http:
          path: project
          method: get
          cors: true
  stripe-cancel-post:
    handler: out/stripe-cancel_post.handler
    events:
      - http:
          path: stripe-cancel
          method: post
          cors: true
  stripe-local-post:
    handler: out/stripe-local_post.handler
    events:
      - http:
          path: stripe-local
          method: post
          cors: true
  stripe-invoice-paid-post:
    handler: out/stripe-invoice-paid_post.handler
    events:
      - http:
          path: stripe-invoice-paid
          method: post
          cors: true
  stripe-is-subscribed:
    handler: out/stripe-is-subscribed_get.handler
    events:
      - http:
          path: stripe-is-subscribed
          method: get
          cors: true
  stripe-payment-method-delete:
    handler: out/stripe-payment-method_delete.handler
    events:
      - http:
          path: stripe-payment-method
          method: delete
          cors: true
  stripe-payment-methods:
    handler: out/stripe-payment-methods_get.handler
    events:
      - http:
          path: stripe-payment-methods
          method: get
          cors: true
  stripe-payment-attached:
    handler: out/stripe-payment-attached_post.handler
    events:
      - http:
          path: stripe-payment-attached
          method: post
          cors: true
  stripe-payment-succeeded:
    handler: out/stripe-payment-succeeded_post.handler
    events:
      - http:
          path: stripe-payment-succeeded
          method: post
          cors: true
  stripe-products-get:
    handler: out/stripe-products_get.handler
    events:
      - http:
          path: stripe-products
          method: get
          cors: true
  stripe-session-post:
    handler: out/stripe-session_post.handler
    events:
      - http:
          path: stripe-session
          method: post
          cors: true
  stripe-setup-succeeded:
    handler: out/stripe-setup-succeeded_post.handler
    events:
      - http:
          path: stripe-setup-succeeded
          method: post
          cors: true
  stripe-setup-intent-post:
    handler: out/stripe-setup-intent_post.handler
    events:
      - http:
          path: stripe-setup-intent
          method: post
          cors: true
  stripe-subscribe-post:
    handler: out/stripe-subscribe_post.handler
    events:
      - http:
          path: stripe-subscribe
          method: post
          cors: true
  stripe-subscriptions-get:
    handler: out/stripe-subscriptions_get.handler
    events:
      - http:
          path: stripe-subscriptions
          method: get
          cors: true
  stripe-user-put:
    handler: out/stripe-user_put.handler
    events:
      - http:
          path: stripe-user
          method: put
          cors: true
  twitter-login-post:
    handler: out/twitter-login_post.handler
    events:
      - http:
          path: twitter-login
          method: post
          cors: true
